### ISSUE TITLE
Make a 3.0.3 release

### ISSUE THREAD

**Issue by MatthewCroughan** [Yubico/yubihsm-connector#36]
Now that https://github.com/Yubico/yubihsm-connector/pull/34 is closed, we need to make a new release, otherwise people can't build 3.0.2 reproducibly from source when using a modern version of Go. A version bump to 3.0.3 based on the latest master should be good.

**Comment by jpreese** [comment]
`v3.0.4` was released earlier this year. Marking as resolved.

ref: https://github.com/Yubico/yubihsm-connector/releases/tag/3.0.4
