### ISSUE TITLE
document how to build for arm/rpi

### ISSUE THREAD

**Issue by klali** [Yubico/yubihsm-connector#6]
/assign @klali

**Comment by trebortech** [comment]
I'm open to testing :)

**Comment by jevonearth** [comment]
Can yubico offer arm builds of the yubihsm SDK? (perhaps we can repurpose this issue to making packages, and have docs as a task within the issue?)

**Comment by qpernil** [comment]
I would just comment that building on 32-bit Raspbian and 64-bit Ubuntu on RPI works without a hitch.
There have even been some 32-bit specific bug fixes along the way.

Closing this issues now since it is so old. Please feel free to reopen if needed.

**Comment by Xelendor1** [comment]
anyway to reopen this? would really like an arm build...

**Comment by qpernil** [comment]
Could you clarify what it is you're missing at the moment ? Instructions, an actual pre-built binary or something else ?
Thx
/per

**Comment by Xelendor1** [comment]
Hello,

I'm trying to run the connector on an ARM based Rockpi.  Currently there
aren't any builds for Yubico hsm sdk for ARM Ubuntu.

Thank you,

Mack

**Comment by qpernil** [comment]
You're right. But it's quite easy to build the yubihsm-shell project on Ubuntu, arm or x86, 64 or 32 bit. I have it running on RPi with the default 32-bit Raspbian Buster, and on Debian 20.10 64 bit. I just built from source. Instructions are here: https://github.com/Yubico/yubihsm-shell. The only difference for the pi is possibly the names of dependencies.

**Comment by Xelendor1** [comment]
Hi Per,

Having some issues with the build.  I have gotten as far as

$ mkdir build && cd build
$ cmake ..
$ make

However the binaries don't seem to work.  Not sure what commands to
run after this.  I thought from this point I could run the connector
with

yubihsm-connector -l localhost:12345

but it looks like the binaries weren't installed yet.


Thanks,

Mack

**Comment by qpernil** [comment]
I see there is a step missing after make - sudo make install. I will get the instructions fixed.

**Comment by Xelendor1** [comment]
Per-fect ;)

**Comment by qpernil** [comment]
Closing this again, as it is presumably fixed

**Comment by Xelendor1** [comment]
Hey sorry i got every thing working. thank you so much!!!!
